// <auto-generated />
namespace RKE.DAL.Concrate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class recreat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recreat));
        
        string IMigrationMetadata.Id
        {
            get { return "201703241049342_recreat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
